name: priocomp
channels:
  - defaults
  - conda-forge
  - anaconda
  - bioconda
  - mutirri
  - gurobi
dependencies:
  - python=3.5*
  - click
  - fiona
  - flake8
  - flask
  - geos=3.4.2
  # NOTE: using gdal>=2.1.0 will break things as gdalwarp does not accept
  # cultine with invalid geometry (such as NUTS data)
  - gdal=2.0.2
  - gurobi
  - joblib  
  - libgdal
  - netcdf4
  - numpy
  - pandas
  - py
  - pypandoc
  - pytest
  - rasterio
  - scipy
  - snakemake
  - Sphinx
  - yaml
  - pip:
      - colorlog
      - easywebdav
      - geopandas
      - python-dotenv
      - rasterstats
      - tabulate
