name: priocomp
channels:
  - defaults
  - bioconda
  - mutirri
  - r
dependencies:
  - python=3.*
  - click
  - flake8
  - GDAL>=2.0.0
  - numpy=1.10
  - rasterio
  - snakemake
  - Sphinx
  - tox
  - pip:
      - easywebdav
      - python-dotenv
