name: priocomp
channels:
  - defaults
  - bioconda
  - mutirri
  - r
  - gurobi
dependencies:
  - python=3.5
  - click
  - fiona
  - flake8
  - flask
  - GDAL>=2.0.0
  - numpy=1.10
  - py
  - pytest
  - rasterio
  - r
  - r-devtools
  - r-ggplot2
  - r-raster
  - r-recommended
  - r-testthat
  - rpy2
  - scipy
  - snakemake
  - Sphinx
  - yaml
  - pip:
      - easywebdav
      - python-dotenv
